import "server-only";
import { AwsClient } from "aws4fetch";
import { createReadStream, existsSync } from "node:fs";
import { mkdir, unlink, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { Readable } from "node:stream";

/**
 * Object storage for attachments.
 *
 * Production uses the platform's MinIO add-on, which injects S3_ENDPOINT /
 * S3_ACCESS_KEY / S3_SECRET_KEY / S3_REGION. That endpoint is an *internal*
 * container hostname with no published port, so browsers can never reach it —
 * every read goes through our own authorized proxy route.
 *
 * With no S3_ENDPOINT (local development) we fall back to the filesystem so the
 * whole upload flow is exercisable without object storage. That fallback is not
 * suitable for the platform: app containers have no persistent volume, so files
 * would vanish on the next deploy.
 *
 * Everything is resolved lazily inside getStorage(), mirroring the lazy Prisma
 * client: `next build` imports this module while collecting routes and must not
 * read env or open a socket.
 */

const BUCKET = "slack-uploads";

export type StorageDriver = {
  put(key: string, body: ArrayBuffer, contentType: string): Promise<void>;
  get(key: string, range?: string | null): Promise<Response>;
  remove(key: string): Promise<void>;
};

function createS3Driver(
  endpoint: string,
  accessKeyId: string,
  secretAccessKey: string,
  region: string,
): StorageDriver {
  const client = new AwsClient({
    accessKeyId,
    secretAccessKey,
    region,
    service: "s3",
  });
  const base = `${endpoint.replace(/\/+$/, "")}/${BUCKET}`;

  // The add-on provisions MinIO but no bucket, so create it once on first use.
  let bucketReady: Promise<void> | null = null;
  function ensureBucket(): Promise<void> {
    bucketReady ??= (async () => {
      const res = await client.fetch(base, { method: "PUT" });
      // 409 = BucketAlreadyOwnedByYou, which is success for our purposes.
      if (!res.ok && res.status !== 409) {
        throw new Error(`Could not create bucket "${BUCKET}" (${res.status})`);
      }
    })();
    return bucketReady;
  }

  return {
    async put(key, body, contentType) {
      await ensureBucket();
      const res = await client.fetch(`${base}/${key}`, {
        method: "PUT",
        body,
        headers: { "content-type": contentType },
      });
      if (!res.ok) {
        throw new Error(`Upload failed (${res.status})`);
      }
    },
    async get(key, range) {
      return client.fetch(`${base}/${key}`, {
        method: "GET",
        headers: range ? { range } : undefined,
      });
    },
    async remove(key) {
      await client.fetch(`${base}/${key}`, { method: "DELETE" }).catch(() => {});
    },
  };
}

function createLocalDriver(): StorageDriver {
  const root = resolve(process.cwd(), ".uploads");
  // Keys are generated by us ("w/<id>/<uuid><ext>"), but never trust a path.
  function pathFor(key: string): string {
    const full = resolve(root, key);
    if (!full.startsWith(root)) throw new Error("Invalid object key");
    return full;
  }

  return {
    async put(key, body, contentType) {
      const p = pathFor(key);
      await mkdir(dirname(p), { recursive: true });
      await writeFile(p, Buffer.from(body));
      await writeFile(`${p}.type`, contentType, "utf8");
    },
    async get(key) {
      const p = pathFor(key);
      if (!existsSync(p)) return new Response(null, { status: 404 });
      const stream = Readable.toWeb(
        createReadStream(p),
      ) as unknown as ReadableStream<Uint8Array>;
      return new Response(stream, { status: 200 });
    },
    async remove(key) {
      const p = pathFor(key);
      await unlink(p).catch(() => {});
      await unlink(`${p}.type`).catch(() => {});
    },
  };
}

let cached: StorageDriver | null = null;

export function getStorage(): StorageDriver {
  if (cached) return cached;
  const endpoint = process.env.S3_ENDPOINT;
  cached = endpoint
    ? createS3Driver(
        endpoint,
        process.env.S3_ACCESS_KEY ?? "",
        process.env.S3_SECRET_KEY ?? "",
        process.env.S3_REGION ?? "us-east-1",
      )
    : createLocalDriver();
  return cached;
}

/** Which driver a request would use — surfaced in logs and the health payload. */
export function storageKind(): "s3" | "local" {
  return process.env.S3_ENDPOINT ? "s3" : "local";
}

export function objectKeyFor(workspaceId: string, extension: string): string {
  return `w/${workspaceId}/${crypto.randomUUID()}${extension}`;
}
